apiVersion: v1
data:
  oidc.keycloak.clientSecret:  <Client Secret from Keycloak OIDC client>
kind: Secret
metadata:
  annotations:
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
type: Opaque
