apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://<argocd-uri>
  oidc.config: |
    name: Keycloak
    issuer: https://<keycloak-uri>/realms/argocd
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "profile", "email"]
    rootCA: <CA certificate if self-signed>